apiVersion: v1
kind: Secret
metadata:
  name: mssql-secret
  labels:
    {{- include "netcandystore.labels" . | nindent 4 }}
stringData:
  SA_PASSWORD: {{ .Values.netcandy.dbpassword | quote }}
  SERVICE_NAME: mssql
