apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pvc
  labels:
    {{- include "netcandystore.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.netcandy.dbstorage }}
