apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Exposes the server
  name: mssql
  labels:
    {{- include "netcandystore.labels" . | nindent 4 }}
spec:
  ports:
  - name: tcp
    port: 1433
    targetPort: 1433
  selector:
    name: mssql
